### ISSUE TITLE
can you help me. how to use gpu?

### ISSUE THREAD

**Issue by zhunipingan** [rpryzant/delete_retrieve_generate#16]
hi,
     I want to use gpu to run the code. As I found that it cost too much time on cpu. but I don't know how to achieve this goals in your code.
    can you tell me how to do? maybe the question is not too hard, but I have tried a lot. thanks!

**Comment by rpryzant** [comment]
Thanks for reaching out! 

So what happens when you run `nvidia-smi` in your bash prompt?

If your GPU is set up properly you should see something like this
https://i.stack.imgur.com/JyWHR.png

and the system should automatically see the gpu and use it. 
(the logic for that is here: https://github.com/rpryzant/delete_retrieve_generate/blob/master/src/cuda.py)

**Comment by zhunipingan** [comment]
Thanks for your timely reply!
I can run on gpu now, it need nearly 1.5h to run one epoch. 
Thank you!!!! best wishes~
